// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/lobby/:lobbyId": {
    params: {
      "lobbyId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/lobby/:lobbyId";
  };
  "./screens/landing-page.tsx": {
    id: "screens/landing-page";
    page: "/";
  };
  "./screens/lobby-page.tsx": {
    id: "screens/lobby-page";
    page: "/lobby/:lobbyId";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "screens/landing-page": typeof import("./src/app/./screens/landing-page.tsx");
  "screens/lobby-page": typeof import("./src/app/./screens/lobby-page.tsx");
};